% Auto-generated by cameraCalibrator app on 02-Oct-2022
%-------------------------------------------------------


% Define images to process
imageFileNames = {
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_1.jpg',...
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_2.jpg',...
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_3.jpg',...
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_4.jpg',...
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_5.jpg',...
%     '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_6.jpg',...
    '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_8.jpg',...
    '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_10.jpg',...
    '/Users/lhwang/Desktop/RBE 3001 repo/RBE3001_Team06/src/cam_clib/image_11.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera using fisheye parameters
[cameraParams, imagesUsed, estimationErrors] = estimateFisheyeParameters(imagePoints, worldPoints, ...
    [mrows, ncols], ...
    'EstimateAlignment', false, ...
    'WorldUnits', 'millimeters');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortFisheyeImage(originalImage, cameraParams.Intrinsics);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
